package js

import _ "embed"

// stdlibBundleSource is the single vendored bundle holding every pure
// JavaScript standard library: BigNumber (bignumber.js), dayjs, fxp
// (fast-xml-parser), radashi, z (zod, with the en and zh-CN locales,
// defaulting to zh-CN), and the core-js URL / URLSearchParams polyfills. It is
// generated by js/libs/build — after editing entry.js or bumping a dependency
// there, rerun `task js:stdlib` (or `npm ci && npm run build` in that
// directory).
//
//go:embed libs/stdlib.bundle.js
var stdlibBundleSource []byte

// stdLibs are the standard libraries installed into every runtime unless the
// engine was built with WithoutStdLibs. The bundle installs each library under
// its ecosystem-native global name — BigNumber, dayjs, fxp, radashi, and z —
// plus the web platform globals URL and URLSearchParams.
var stdLibs = []Lib{
	ProgramLib("stdlib", MustCompile("stdlib", string(stdlibBundleSource), true)),
}
