package orm

// ConstraintKind identifies the type of column constraint.
type ConstraintKind int

const (
	ConstraintNotNull ConstraintKind = iota
	ConstraintNullable
	ConstraintDefault
	ConstraintPrimaryKey
	ConstraintUnique
	ConstraintAutoIncrement
	ConstraintCheck
	ConstraintReferences
)

// ColumnConstraint represents a SQL column constraint such as NOT NULL, DEFAULT, PRIMARY KEY, etc.
type ColumnConstraint struct {
	kind         ConstraintKind
	defaultValue any
	checkBuilder func(ConditionBuilder)
	refTable     string
	refColumns   []string
}

// NotNull creates a NOT NULL column constraint.
func NotNull() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintNotNull}
}

// Nullable creates an explicit NULL column constraint.
func Nullable() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintNullable}
}

// Default creates a DEFAULT column constraint with the given value.
func Default(value any) ColumnConstraint {
	return ColumnConstraint{kind: ConstraintDefault, defaultValue: value}
}

// PrimaryKey creates a PRIMARY KEY column constraint.
func PrimaryKey() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintPrimaryKey}
}

// Unique creates a UNIQUE column constraint.
func Unique() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintUnique}
}

// AutoIncrement creates an auto-increment column constraint.
// PostgreSQL: GENERATED BY DEFAULT AS IDENTITY, MySQL: AUTO_INCREMENT, SQLite: AUTOINCREMENT.
func AutoIncrement() ColumnConstraint {
	return ColumnConstraint{kind: ConstraintAutoIncrement}
}

// Check creates a CHECK column constraint using the ConditionBuilder.
func Check(builder func(ConditionBuilder)) ColumnConstraint {
	return ColumnConstraint{kind: ConstraintCheck, checkBuilder: builder}
}

// References creates an inline foreign key column constraint.
func References(table string, columns ...string) ColumnConstraint {
	return ColumnConstraint{kind: ConstraintReferences, refTable: table, refColumns: columns}
}
