package security

import (
	"context"

	"github.com/coldsmirk/vef-framework-go/result"
)

// OTPEvaluator determines whether a user needs OTP verification.
type OTPEvaluator interface {
	// Evaluate checks the principal and returns challenge data if OTP is required.
	// Return nil to skip the challenge; non-nil triggers a challenge.
	Evaluate(ctx context.Context, principal *Principal) (*OTPChallengeData, error)
}

// OTPCodeSender triggers OTP code delivery.
// For TOTP this is nil (codes are generated by an authenticator app);
// for SMS/Email this sends the code through the chosen channel.
type OTPCodeSender interface {
	// Send triggers the delivery of an OTP code to the given principal.
	Send(ctx context.Context, principal *Principal) error
}

// OTPCodeVerifier validates a user-submitted OTP code.
type OTPCodeVerifier interface {
	// Verify checks whether the submitted code is valid for the given principal.
	Verify(ctx context.Context, principal *Principal, code string) (bool, error)
}

// OTPCodeStore manages the lifecycle of server-generated OTP codes.
// Used for SMS/Email flows where the server generates, stores, and verifies codes.
type OTPCodeStore interface {
	// Generate creates a new OTP code, stores it, and returns the generated code.
	Generate(ctx context.Context, principal *Principal) (string, error)
	// Verify checks whether the submitted code matches the stored code.
	Verify(ctx context.Context, principal *Principal, code string) (bool, error)
}

// OTPCodeDelivery sends a generated OTP code to the user through a specific channel (SMS, email, etc.).
type OTPCodeDelivery interface {
	// Deliver sends the given OTP code to the principal via the configured channel.
	Deliver(ctx context.Context, principal *Principal, code string) error
}

// OTPChallengeData describes metadata presented to the user for an OTP challenge.
type OTPChallengeData struct {
	Destination string         `json:"destination"`
	Meta        map[string]any `json:"meta,omitempty"`
}

// OTPChallengeProviderConfig configures an OTPChallengeProvider.
type OTPChallengeProviderConfig struct {
	ChallengeType  string          // Required, unique identifier (e.g. "totp", "sms_otp").
	ChallengeOrder int             // Evaluation priority; lower values are evaluated first.
	Evaluator      OTPEvaluator    // Required.
	Sender         OTPCodeSender   // Optional; nil skips the send step.
	Verifier       OTPCodeVerifier // Required.
}

// OTPChallengeProvider orchestrates OTP evaluation, sending, and verification.
// It implements the ChallengeProvider interface.
type OTPChallengeProvider struct {
	config OTPChallengeProviderConfig
}

// NewOTPChallengeProvider creates a generic OTP challenge provider.
// ChallengeType, Evaluator, and Verifier are required; panics if any is missing.
func NewOTPChallengeProvider(config OTPChallengeProviderConfig) *OTPChallengeProvider {
	if config.ChallengeType == "" {
		panic("security: OTPChallengeProviderConfig.ChallengeType is required")
	}
	if config.Evaluator == nil {
		panic("security: OTPChallengeProviderConfig.Evaluator is required")
	}
	if config.Verifier == nil {
		panic("security: OTPChallengeProviderConfig.Verifier is required")
	}

	return &OTPChallengeProvider{config: config}
}

func (p *OTPChallengeProvider) Type() string { return p.config.ChallengeType }
func (p *OTPChallengeProvider) Order() int   { return p.config.ChallengeOrder }

func (p *OTPChallengeProvider) Evaluate(ctx context.Context, principal *Principal) (*LoginChallenge, error) {
	data, err := p.config.Evaluator.Evaluate(ctx, principal)
	if err != nil || data == nil {
		return nil, err
	}

	if p.config.Sender != nil {
		if err := p.config.Sender.Send(ctx, principal); err != nil {
			return nil, err
		}
	}

	return &LoginChallenge{
		Type:     p.config.ChallengeType,
		Data:     data,
		Required: true,
	}, nil
}

func (p *OTPChallengeProvider) Resolve(ctx context.Context, principal *Principal, response any) (*Principal, error) {
	code, ok := response.(string)
	if !ok || code == "" {
		return nil, result.ErrOTPCodeRequired
	}

	valid, err := p.config.Verifier.Verify(ctx, principal, code)
	if err != nil {
		return nil, err
	}
	if !valid {
		return nil, result.ErrOTPCodeInvalid
	}

	return principal, nil
}

// DeliveredCodeSender orchestrates OTPCodeStore and OTPCodeDelivery to implement OTPCodeSender.
// Flow: generate code -> store it -> deliver through the channel.
type DeliveredCodeSender struct {
	store    OTPCodeStore
	delivery OTPCodeDelivery
}

// NewDeliveredCodeSender creates a DeliveredCodeSender that generates codes via store and sends them via delivery.
func NewDeliveredCodeSender(store OTPCodeStore, delivery OTPCodeDelivery) *DeliveredCodeSender {
	return &DeliveredCodeSender{store: store, delivery: delivery}
}

func (s *DeliveredCodeSender) Send(ctx context.Context, principal *Principal) error {
	code, err := s.store.Generate(ctx, principal)
	if err != nil {
		return err
	}

	return s.delivery.Deliver(ctx, principal, code)
}

// DeliveredCodeVerifier delegates to OTPCodeStore to verify codes, implementing OTPCodeVerifier.
type DeliveredCodeVerifier struct {
	store OTPCodeStore
}

// NewDeliveredCodeVerifier creates a DeliveredCodeVerifier backed by the given store.
func NewDeliveredCodeVerifier(store OTPCodeStore) *DeliveredCodeVerifier {
	return &DeliveredCodeVerifier{store: store}
}

func (v *DeliveredCodeVerifier) Verify(ctx context.Context, principal *Principal, code string) (bool, error) {
	return v.store.Verify(ctx, principal, code)
}

// Challenge type constants for convenience constructors.
const (
	ChallengeTypeSMS   = "sms_otp"
	ChallengeTypeEmail = "email_otp"
)

// NewDeliveredChallengeProvider creates an OTP challenge provider backed by OTPCodeStore and OTPCodeDelivery.
func NewDeliveredChallengeProvider(challengeType string, order int, evaluator OTPEvaluator, store OTPCodeStore, delivery OTPCodeDelivery) *OTPChallengeProvider {
	return NewOTPChallengeProvider(OTPChallengeProviderConfig{
		ChallengeType:  challengeType,
		ChallengeOrder: order,
		Evaluator:      evaluator,
		Sender:         NewDeliveredCodeSender(store, delivery),
		Verifier:       NewDeliveredCodeVerifier(store),
	})
}

// NewSMSChallengeProvider creates an SMS OTP challenge provider.
// Default type "sms_otp", order 200.
func NewSMSChallengeProvider(evaluator OTPEvaluator, store OTPCodeStore, delivery OTPCodeDelivery) *OTPChallengeProvider {
	return NewDeliveredChallengeProvider(ChallengeTypeSMS, 200, evaluator, store, delivery)
}

// NewEmailChallengeProvider creates an Email OTP challenge provider.
// Default type "email_otp", order 300.
func NewEmailChallengeProvider(evaluator OTPEvaluator, store OTPCodeStore, delivery OTPCodeDelivery) *OTPChallengeProvider {
	return NewDeliveredChallengeProvider(ChallengeTypeEmail, 300, evaluator, store, delivery)
}
