package security

import (
	"cmp"
	"context"
	"errors"
	"fmt"
	"slices"
	"strings"
	"time"

	"github.com/coldsmirk/go-collections"
	"github.com/coldsmirk/go-streams"
	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/extractors"
	"go.uber.org/fx"

	"github.com/coldsmirk/vef-framework-go/api"
	"github.com/coldsmirk/vef-framework-go/config"
	"github.com/coldsmirk/vef-framework-go/contextx"
	"github.com/coldsmirk/vef-framework-go/event"
	"github.com/coldsmirk/vef-framework-go/fiberx"
	"github.com/coldsmirk/vef-framework-go/i18n"
	"github.com/coldsmirk/vef-framework-go/lock"
	"github.com/coldsmirk/vef-framework-go/result"
	"github.com/coldsmirk/vef-framework-go/security"
)

// AuthResourceParams holds the dependencies for AuthResource construction.
type AuthResourceParams struct {
	fx.In

	AuthManager         security.AuthManager
	TokenGenerator      security.TokenGenerator
	ChallengeTokenStore security.ChallengeTokenStore
	Locker              lock.Locker
	UserInfoLoader      security.UserInfoLoader `optional:"true"`
	LoginGuard          security.LoginGuard     `optional:"true"`
	SessionStore        security.SessionStore
	RevocationNotifier  *security.SessionRevocationNotifier `optional:"true"`
	ChallengeProviders  []security.ChallengeProvider        `group:"vef:security:challenge_providers"`
	Bus                 event.Bus
	SecurityConfig      *config.SecurityConfig
}

// NewAuthResource creates a new authentication resource with the provided auth manager and token generator.
func NewAuthResource(params AuthResourceParams) api.Resource {
	slices.SortFunc(params.ChallengeProviders, func(a, b security.ChallengeProvider) int {
		return cmp.Compare(a.Order(), b.Order())
	})

	operations := []api.OperationSpec{
		{
			Action:    "login",
			Public:    true,
			RateLimit: &api.RateLimitConfig{Max: params.SecurityConfig.LoginRateLimit},
		},
	}

	// The refresh flow exists only under the stateless JWT mechanism; an opaque
	// session renews itself on use, so the operation is not mounted at all.
	if params.SecurityConfig.EffectiveTokenType() == config.TokenTypeJWT {
		operations = append(operations, api.OperationSpec{
			Action:    "refresh",
			Public:    true,
			RateLimit: &api.RateLimitConfig{Max: params.SecurityConfig.RefreshRateLimit},
		})
	}

	operations = append(operations,
		api.OperationSpec{
			Action: "logout",
		},
		api.OperationSpec{
			Action:    "resolve_challenge",
			Public:    true,
			RateLimit: &api.RateLimitConfig{Max: params.SecurityConfig.LoginRateLimit},
		},
		api.OperationSpec{
			Action: "get_user_info",
		},
	)

	return &AuthResource{
		authManager:         params.AuthManager,
		tokenGenerator:      params.TokenGenerator,
		challengeTokenStore: params.ChallengeTokenStore,
		locker:              params.Locker,
		userInfoLoader:      params.UserInfoLoader,
		loginGuard:          params.LoginGuard,
		sessionStore:        params.SessionStore,
		revocationNotifier:  params.RevocationNotifier,
		challengeProviders:  params.ChallengeProviders,
		bus:                 params.Bus,

		Resource: api.NewRPCResource(
			"security/auth",
			api.WithOperations(operations...),
		),
	}
}

// AuthResource handles authentication-related API endpoints.
type AuthResource struct {
	api.Resource

	authManager         security.AuthManager
	tokenGenerator      security.TokenGenerator
	challengeTokenStore security.ChallengeTokenStore
	locker              lock.Locker
	userInfoLoader      security.UserInfoLoader
	loginGuard          security.LoginGuard
	sessionStore        security.SessionStore
	revocationNotifier  *security.SessionRevocationNotifier
	challengeProviders  []security.ChallengeProvider
	bus                 event.Bus
}

// LoginParams represents the request parameters for user login.
type LoginParams struct {
	api.P

	Type        string `json:"type" validate:"required" label_i18n:"auth_type"`
	Principal   string `json:"principal" validate:"required" label_i18n:"auth_principal"`
	Credentials any    `json:"credentials" validate:"required" label_i18n:"auth_credentials"`
}

// internalTokenAuthTypes are the mechanisms whose credentials the framework
// itself issues. Login refuses them: exchanging an issued token for a fresh
// token pair would let a stolen short-lived access token be laundered into a
// long-lived refresh token or an additional server-side session.
var internalTokenAuthTypes = collections.NewHashSetFrom(AuthTypeJWTToken, AuthTypeOpaqueToken, AuthTypeRefresh)

// unguessableAuthTypes are the login mechanisms the brute-force guard is
// skipped for, because guessing their credential is not a threat it can help
// with and counting the attempts costs more than it buys.
//
// A trust code is the one such mechanism today: it is generated by
// GenerateOpaqueToken, redeemable once, and expires in seconds, so no number of
// attempts approaches it. What the guard would do instead is harmful. The
// identity presented on this path is the initiating system's app ID, not a
// person, so under vef.security.lockout.key = "user" a single bucket stands for
// every user of that system — and anyone able to POST a wrong code could shut
// single sign-on off for all of them. The throttles that do apply here are the
// gateway's own rate limit, the code's single use, and the login endpoint's
// vef.security.login_rate_limit.
//
// This is deliberately not folded into the guard helpers themselves: those are
// shared with ResolveChallenge, whose steps carry the same login mechanism but
// guess something else — the answer to a challenge, which very much is
// guessable. A trust-code login's challenge steps therefore stay counted
// (TestTrustCodeChallengeLockout) — under the account being logged into rather
// than the app ID, for the same reason the login step is exempt (see
// challengeAttemptIdentity).
var unguessableAuthTypes = collections.NewHashSetFrom(security.AuthTypeTrustCode)

// challengeAttemptIdentity returns the identity a resolve_challenge step counts
// brute-force attempts under: the one its login step counts under.
//
// A mechanism the login step guards counts under the identifier presented, so a
// password login's challenge guesses and password guesses share one bucket, and a
// lockout tripped by either blocks both endpoints. A mechanism exempt at login
// has no login-step bucket, and the identifier it presents names no account: a
// trust code presents the initiating system's app ID, so counting under it would
// let one user's wrong answers lock the challenge step for every user that system
// hands off — or, under lockout.key = "user_ip", for everyone behind the same
// address. Its challenge steps count under the account instead.
func challengeAttemptIdentity(login *security.LoginContext) string {
	if unguessableAuthTypes.Contains(login.AuthType) {
		return login.Principal.ID
	}

	return login.Username
}

// Login authenticates a user and returns a LoginResult.
// When challenge providers are configured and applicable, the result contains
// a challenge token and pending challenges instead of auth tokens.
func (a *AuthResource) Login(ctx fiber.Ctx, params LoginParams) error {
	if internalTokenAuthTypes.Contains(params.Type) {
		return errUnsupportedAuthenticationType(params.Type)
	}

	audit := security.LoginEventParams{AuthType: params.Type, Username: params.Principal}
	attempt := security.LoginAttempt{Identity: params.Principal, ClientIP: fiberx.GetIP(ctx)}
	guarded := !unguessableAuthTypes.Contains(params.Type)

	if guarded {
		if locked := a.guardCheck(ctx, audit, attempt); locked != nil {
			return locked
		}
	}

	principal, err := a.authManager.Authenticate(ctx.Context(), security.Authentication{
		Type:        params.Type,
		Principal:   params.Principal,
		Credentials: params.Credentials,
	})
	if err != nil {
		// A reserved-identity rejection means an authenticator resolved a
		// framework-internal identity: the credential may well have been correct,
		// so the fault is the authenticator's, not the caller's, and counting it
		// would let a buggy extension lock the user out. Audited but not counted,
		// exactly like the analogous gate in ResolveChallenge.
		if guarded && !errors.Is(err, errReservedPrincipalRejected) {
			a.guardRecordFailure(ctx, attempt)
		}

		a.publishLoginFailure(ctx, audit, err)

		return err
	}

	// The failures a login counted are cleared only once it completes, so the
	// attempt travels with the login instead of being cleared here (see
	// guardRecordSuccess). A mechanism this step exempts counted nothing under the
	// identifier it presented, so it has no bucket to clear.
	var counted *security.LoginAttempt
	if guarded {
		counted = &attempt
	}

	pending := streams.MapTo(
		streams.FromSlice(a.challengeProviders),
		func(p security.ChallengeProvider) string { return p.Type() },
	).Collect()

	// A memory-backed challenge token store keeps this state for minutes after
	// the request, yet neither string needs a copy: params are decoded from JSON,
	// which allocates every string rather than viewing the pooled request buffer.
	state := &security.ChallengeState{
		AuthType:  params.Type,
		Username:  params.Principal,
		Principal: principal,
		Pending:   pending,
	}

	return a.advanceLogin(ctx, state, audit, counted)
}

// RefreshParams represents the request parameters for token refresh operation.
type RefreshParams struct {
	api.P

	RefreshToken string `json:"refreshToken" validate:"required" label_i18n:"auth_refresh_token"`
}

// Refresh refreshes the access token using a valid refresh token.
// User data reload logic is handled by JwtRefreshAuthenticator.
func (a *AuthResource) Refresh(ctx fiber.Ctx, params RefreshParams) error {
	principal, err := a.authManager.Authenticate(ctx.Context(), security.Authentication{
		Type:      AuthTypeRefresh,
		Principal: params.RefreshToken,
	})
	if err != nil {
		return err
	}

	credentials, err := a.tokenGenerator.Generate(ctx.Context(), principal, sessionMeta(ctx))
	if err != nil {
		return err
	}

	return result.Ok(credentials).Response(ctx)
}

// Logout revokes the opaque session backing the presented token so it can no
// longer authenticate. Under the stateless JWT mechanism no session exists, so
// it is a no-op and clients must drop their stored tokens.
func (a *AuthResource) Logout(ctx fiber.Ctx) error {
	a.revokeCurrentSession(ctx)

	return result.Ok().Response(ctx)
}

// revokeCurrentSession revokes the session for the presented bearer token, if
// one exists. It is best-effort: a missing session (JWT, already expired) or a
// store error never fails logout.
func (a *AuthResource) revokeCurrentSession(ctx fiber.Ctx) {
	token := extractBearerToken(ctx)
	if token == "" {
		return
	}

	session, err := a.sessionStore.Lookup(ctx.Context(), security.HashOpaqueToken(token))
	if err != nil || session == nil {
		return
	}

	if err := a.sessionStore.Revoke(ctx.Context(), session.ID); err != nil {
		logger.Warnf("Failed to revoke session on logout: %v", err)

		return
	}

	a.revocationNotifier.NotifyRevoked(ctx.Context(),
		security.SessionRevocation{SessionID: session.ID, UserID: session.UserID})
}

// ResolveChallengeParams represents the request for resolving a login challenge.
type ResolveChallengeParams struct {
	api.P

	ChallengeToken string `json:"challengeToken" validate:"required" label_i18n:"auth_challenge_token"`
	Type           string `json:"type" validate:"required" label_i18n:"auth_challenge_type"`
	Response       any    `json:"response" validate:"required" label_i18n:"auth_challenge_response"`
}

// ResolveChallenge validates a user's response to a login challenge.
// On success, either issues real auth tokens (all challenges resolved)
// or evaluates the next challenge sequentially. A challenge token resolves at
// most one step, whichever store issued it (see claimChallengeToken).
//
// A ChallengeProvider may reject a response by returning a typed result.Error
// (e.g. security.ErrOTPCodeInvalid) to control the client-facing code; a bare
// error is normalized to security.ErrChallengeResolveFailed (code
// security.ErrCodeChallengeResolveFailed).
func (a *AuthResource) ResolveChallenge(ctx fiber.Ctx, params ResolveChallengeParams) error {
	// A state without its login mechanism is refused like a token that does not
	// parse, whichever store produced it: every filtered provider would otherwise
	// be evaluated against a login none of them names, and allow-listed challenges
	// would be skipped.
	state, err := a.challengeTokenStore.Parse(ctx.Context(), params.ChallengeToken)
	if err != nil || state.AuthType == "" {
		return security.ErrChallengeTokenInvalid
	}

	if len(state.Pending) == 0 || state.Pending[0] != params.Type {
		return security.ErrChallengeTypeInvalid
	}

	provider := a.findProvider(params.Type)
	if provider == nil {
		return security.ErrChallengeTypeInvalid
	}

	// provider.Resolve is the second-factor analog of authManager.Authenticate:
	// a rejection here is a genuine failed credential attempt, so gate it with
	// the brute-force guard and audit it like a failed login — otherwise an
	// attacker holding a valid password could guess the second factor bounded
	// only by the endpoint rate limit. The earlier guards (invalid/expired
	// token, wrong type) are protocol/tampering errors that Login's analogous
	// infra paths do not audit, so they are deliberately left unguarded.
	audit := security.LoginEventParams{AuthType: state.AuthType, Username: state.Username, ChallengeType: params.Type}
	attempt := security.LoginAttempt{Identity: challengeAttemptIdentity(&state.LoginContext), ClientIP: fiberx.GetIP(ctx)}

	if locked := a.guardCheck(ctx, audit, attempt); locked != nil {
		return locked
	}

	claim, err := a.claimChallengeToken(ctx.Context(), params.ChallengeToken)
	if err != nil {
		return err
	}

	principal, err := provider.Resolve(ctx.Context(), &state.LoginContext, params.Response)
	if err != nil {
		releaseChallengeClaim(ctx.Context(), claim)
		a.guardRecordFailure(ctx, attempt)

		// Providers that return a typed result.Error keep their chosen code
		// (e.g. ErrOTPCodeInvalid); a bare error is normalized to the stable
		// challenge-resolve-failed code so the framework never leaks an opaque
		// 500 from a custom ChallengeProvider.
		if _, ok := result.AsErr(err); !ok {
			err = security.ErrChallengeResolveFailed
		}

		a.publishLoginFailure(ctx, audit, err)

		return err
	}

	// A ChallengeProvider's result is vetted by no authenticator, so the resolve
	// path needs its own reserved-identity gate (token issuance downstream stays
	// as defense in depth). The rejection is audited but not counted toward
	// lockout: the second factor was correct — the fault is the provider's, not
	// the caller's. Its claim is kept all the same, because Resolve returned
	// without error: whatever it did — a password set, a code consumed, a
	// department chosen — is already committed, so a replay of this token would do
	// it again, and the retry a release would allow rescues nobody, since the same
	// provider at the same step resolves the same reserved identity.
	if principal == nil || principal.IsReserved() {
		logger.Errorf("Challenge rejected: provider %q resolved to a nil or framework-reserved principal", params.Type)

		a.publishLoginFailure(ctx, audit, security.ErrReservedPrincipal)

		return security.ErrReservedPrincipal
	}

	// Resolve succeeded, so its claim is kept: the unreleased lease marks the
	// token spent from here on (see claimChallengeToken). The failures counted
	// under this identity stay, since a step is not a login: only the step that
	// completes the login clears them (see guardRecordSuccess).
	state.Principal = principal
	state.Resolved = append(state.Resolved, params.Type)
	state.Pending = state.Pending[1:]

	return a.advanceLogin(ctx, state, audit, &attempt)
}

// GetUserInfo retrieves user information via UserInfoLoader.
// Requires a UserInfoLoader implementation to be provided.
func (a *AuthResource) GetUserInfo(ctx fiber.Ctx, principal *security.Principal, params api.Params) error {
	if a.userInfoLoader == nil {
		return result.ErrNotImplemented(i18n.T(security.ErrMessageUserInfoLoaderNotImplemented))
	}

	userInfo, err := a.userInfoLoader.LoadUserInfo(ctx.Context(), principal, params)
	if err != nil {
		return err
	}

	return result.Ok(userInfo).Response(ctx)
}

// publishLoginSuccess publishes a successful-login audit event for the login
// audit describes. Each handler builds audit once from the login it serves — the
// mechanism and the identifier first presented, plus the challenge being
// resolved on a resolve_challenge step — so every event one login raises, on
// whichever step, reports that same login.
func (a *AuthResource) publishLoginSuccess(ctx fiber.Ctx, audit security.LoginEventParams, principal *security.Principal) {
	audit.UserID = &principal.ID
	audit.IsOk = true

	a.publishLoginEvent(ctx, audit)
}

// publishLoginFailure publishes a failed-login audit event for the login audit
// describes, deriving the failure reason and business code from err. It mirrors
// publishLoginSuccess so authentication and challenge-step failures land in the
// same audit pipeline with the same login semantics.
func (a *AuthResource) publishLoginFailure(ctx fiber.Ctx, audit security.LoginEventParams, err error) {
	audit.FailReason = err.Error()
	audit.ErrorCode = result.ErrCodeUnknown

	if resErr, ok := result.AsErr(err); ok {
		audit.FailReason = resErr.Message
		audit.ErrorCode = resErr.Code
	}

	a.publishLoginEvent(ctx, audit)
}

// publishLoginEvent stamps where the attempt came from and publishes it. This
// event is published asynchronously, so a subscriber reads it once the request
// that raised it is long gone — every origin value must therefore be a copy
// rather than a view into the pooled request buffer. The client address and the
// request id already are: fiberx.GetIP and the logger middleware's request-id
// boundary copy on the way out. The User-Agent is read straight off the request
// here, so it is copied here.
func (a *AuthResource) publishLoginEvent(ctx fiber.Ctx, params security.LoginEventParams) {
	params.LoginIP = fiberx.GetIP(ctx)
	params.UserAgent = strings.Clone(ctx.Get(fiber.HeaderUserAgent))
	params.TraceID = contextx.RequestID(ctx)

	_ = a.bus.Publish(ctx.Context(), security.NewLoginEvent(params), event.WithAsync())
}

// guardCheck consults the brute-force guard before authentication. It returns a
// non-nil error to abort the login when the identity is currently locked out,
// and nil to proceed. A nil guard (lockout disabled) or a guard backend failure
// both fail open so an unavailable counter store never denies every login; the
// backend error is logged. A lockout is audited as a failure of the login audit
// describes.
func (a *AuthResource) guardCheck(ctx fiber.Ctx, audit security.LoginEventParams, attempt security.LoginAttempt) error {
	if a.loginGuard == nil {
		return nil
	}

	decision, err := a.loginGuard.Check(ctx.Context(), attempt)
	if err != nil {
		logger.Warnf("Login guard check failed for %s, allowing attempt: %v", maskPrincipal(attempt.Identity), err)

		return nil
	}

	if decision.Allowed {
		return nil
	}

	lockErr := security.ErrAccountLocked(decision.RetryAfter)
	a.publishLoginFailure(ctx, audit, lockErr)

	return lockErr
}

// guardRecordFailure registers a failed attempt with the guard. Failures to
// persist are logged but never surfaced: the guard is defense-in-depth, not the
// authoritative auth result.
func (a *AuthResource) guardRecordFailure(ctx fiber.Ctx, attempt security.LoginAttempt) {
	if a.loginGuard == nil {
		return
	}

	if _, err := a.loginGuard.RecordFailure(ctx.Context(), attempt); err != nil {
		logger.Warnf("Login guard failed to record failure for %s: %v", maskPrincipal(attempt.Identity), err)
	}
}

// guardRecordSuccess clears the failures a login counted, and is called only
// once that login completes — when its tokens are issued, never when the
// credential verifies or an intermediate challenge step succeeds.
//
// Failures count across the whole login: a wrong password and a wrong challenge
// answer fill one bucket (see challengeAttemptIdentity), so clearing earlier
// would leave the second factor bounded by nothing but the endpoint rate limit.
// Anyone holding the password could reset the count of answer guesses by logging
// in again, and an early, easily answered step would reset the guesses of every
// step behind it.
func (a *AuthResource) guardRecordSuccess(ctx fiber.Ctx, attempt security.LoginAttempt) {
	if a.loginGuard == nil {
		return
	}

	if err := a.loginGuard.RecordSuccess(ctx.Context(), attempt); err != nil {
		logger.Warnf("Login guard failed to clear failures for %s: %v", maskPrincipal(attempt.Identity), err)
	}
}

// sessionMeta captures the client context recorded on a session at token issue.
// The session outlives the request that opened it by up to its whole maximum
// lifetime, so neither value may be a view into the pooled request buffer. The
// client address is already copied by fiberx.GetIP; the User-Agent is read
// straight off the request, so it is copied here.
func sessionMeta(ctx fiber.Ctx) security.SessionMeta {
	return security.SessionMeta{
		ClientIP:  fiberx.GetIP(ctx),
		UserAgent: strings.Clone(ctx.Get(fiber.HeaderUserAgent)),
	}
}

// logoutTokenExtractor mirrors the bearer auth strategy's extraction exactly
// (case-insensitive scheme match, header then query) so the token logout revokes
// can never diverge from the token the request authenticated with.
var logoutTokenExtractor = extractors.Chain(
	extractors.FromAuthHeader(security.AuthSchemeBearer),
	extractors.FromQuery(security.QueryKeyAccessToken),
)

// extractBearerToken reads the presented access token, or "" when absent.
func extractBearerToken(ctx fiber.Ctx) string {
	token, _ := logoutTokenExtractor.Extract(ctx)

	return token
}

// findProvider returns the challenge provider matching the given type, or nil.
func (a *AuthResource) findProvider(challengeType string) security.ChallengeProvider {
	return streams.FromSlice(a.challengeProviders).
		FindFirst(func(cp security.ChallengeProvider) bool {
			return cp.Type() == challengeType
		}).
		GetOrElse(nil)
}

// advanceLogin carries an authenticated login to its next step: the next pending
// challenge that applies, handed to the client under a fresh challenge token, or
// the issued tokens once no challenge remains.
//
// Everything here happens after the credential — and, on a resolve step, the
// challenge answer — was accepted, so a failure is audited as a failure of the
// login audit describes but never counted toward lockout: a provider that cannot
// evaluate, a challenge store that cannot issue, and token issuance refused by
// session policy (ErrTooManyConcurrentSessions) are none of them a wrong guess.
//
// Issuing the tokens is what completes the login, so it is also where the
// failures the login counted are cleared: counted names the attempt whose bucket
// they filled, and is nil for a login that counted none. Handing back a challenge
// leaves them standing, and so does failing here.
func (a *AuthResource) advanceLogin(
	ctx fiber.Ctx,
	state *security.ChallengeState,
	audit security.LoginEventParams,
	counted *security.LoginAttempt,
) error {
	challenge, err := a.evaluateNextChallenge(ctx.Context(), state)
	if err != nil {
		a.publishLoginFailure(ctx, audit, err)

		return err
	}

	if challenge != nil {
		challengeToken, err := a.challengeTokenStore.Generate(ctx.Context(), state)
		if err != nil {
			a.publishLoginFailure(ctx, audit, err)

			return err
		}

		return result.Ok(&security.LoginResult{
			ChallengeToken: challengeToken,
			Challenge:      challenge,
		}).Response(ctx)
	}

	tokens, err := a.tokenGenerator.Generate(ctx.Context(), state.Principal, sessionMeta(ctx))
	if err != nil {
		a.publishLoginFailure(ctx, audit, err)

		return err
	}

	if counted != nil {
		a.guardRecordSuccess(ctx, *counted)
	}

	a.publishLoginSuccess(ctx, audit, state.Principal)

	return result.Ok(&security.LoginResult{Tokens: tokens}).Response(ctx)
}

// evaluateNextChallenge walks state.Pending in order and returns the first
// challenge that applies to the login, leaving its type at the head of Pending.
// Types with no registered provider, or whose provider returns nil (challenge
// not needed), are dropped from Pending; nil means none applies.
func (a *AuthResource) evaluateNextChallenge(ctx context.Context, state *security.ChallengeState) (*security.LoginChallenge, error) {
	for ; len(state.Pending) > 0; state.Pending = state.Pending[1:] {
		provider := a.findProvider(state.Pending[0])
		if provider == nil {
			continue
		}

		challenge, err := provider.Evaluate(ctx, &state.LoginContext)
		if err != nil {
			return nil, err
		}

		if challenge != nil {
			return challenge, nil
		}
	}

	return nil, nil
}

const (
	// challengeClaimPrefix reserves the lock namespace a resolve_challenge step
	// claims its challenge token under.
	challengeClaimPrefix = "vef:security:challenge:"
	// challengeClaimTTLBuffer keeps a spent token's claim alive past the token's
	// own lifetime: the JWT parser accepts a token for its leeway past exp, and
	// replicas' clocks drift. Same shape as the signature nonce TTL buffer.
	challengeClaimTTLBuffer = time.Minute
)

// claimChallengeToken claims the presented challenge token for the
// resolve_challenge step presenting it, so a token resolves at most one step
// whichever ChallengeTokenStore issued it. The claim is a lease on the
// lock.Locker, taken after the protocol checks and the brute-force guard but
// before the challenge provider runs: a replay of a step that already ran the
// provider, or a duplicate racing one in flight, finds the lease held and is
// refused as ErrChallengeTokenInvalid before any provider side effect runs
// again — spending the token only after Resolve would still let a leaked
// password_change token set the password. Like the other token refusals, it is
// neither audited nor counted, and clears no lockout failures. A locker backend
// error fails closed.
//
// The caller releases the claim only when provider.Resolve did not succeed — a
// rejected answer, a provider error — so a mistyped code or a password that fails
// policy stays retryable on the same token, with the guard bounding those
// attempts. Once Resolve has returned a principal the claim is kept whatever the
// step then makes of it, a reserved-identity refusal included: its side effects
// are committed by then, and a replay would run them again. The unreleased lease
// is the spent marker, outliving the token by challengeClaimTTLBuffer, so any
// failure after Resolve — the refusal, or anything while advancing the login —
// leaves the token spent and the user starts over at login.
//
// Without Redis the default locker is in-process, so the claim holds per replica
// only; the lock module warns about that at boot.
func (a *AuthResource) claimChallengeToken(ctx context.Context, token string) (lock.Lock, error) {
	claim, err := a.locker.TryAcquire(ctx,
		challengeClaimPrefix+security.HashOpaqueToken(token),
		lock.WithTTL(security.ChallengeTokenExpires+challengeClaimTTLBuffer),
	)
	if errors.Is(err, lock.ErrNotAcquired) {
		return nil, security.ErrChallengeTokenInvalid
	}

	if err != nil {
		return nil, fmt.Errorf("failed to claim challenge token: %w", err)
	}

	return claim, nil
}

// releaseChallengeClaim gives back the claim of a step whose provider.Resolve did
// not succeed, on a context the request's cancellation cannot abort, since a
// release lost to a client disconnect would leave the token spent. A failed
// release is only logged: the lease still expires on its own.
func releaseChallengeClaim(ctx context.Context, claim lock.Lock) {
	if err := claim.Release(context.WithoutCancel(ctx)); err != nil {
		logger.Warnf("Failed to release challenge token claim: %v", err)
	}
}
